# Generated by Django 6.1.1 on 2026-09-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notas', models.TextField(blank=True, default='')),
            ],
        ),
    ]
