# Generated by Django 6.1.1 on 2026-09-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estatura',
            field=models.IntegerField(help_text='En centímetros'),
        ),
    ]
