# Generated by Django 6.1.1 on 2026-09-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack'), ('postre', 'Postre')], default='almuerzo', max_length=20)),
                ('calorias', models.PositiveIntegerField(default=0)),
                ('proteinas_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbos_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grasas_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('receta', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
