# Generated by Django 6.1.1 on 2026-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack')], default='', max_length=20)),
                ('calorias', models.IntegerField(blank=True, null=True)),
                ('proteinas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('carbos_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('grasas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('receta', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
