# Generated by Django 6.1.1 on 2026-09-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='ejercicios',
            field=models.ManyToManyField(blank=True, related_name='entrenamientos', to='gym.set', verbose_name='Ejercicios'),
        ),
    ]
