# Generated by Django 6.1.1 on 2026-09-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_ejercicio'),
        ('workouts', '0002_workout_ejercicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('nivel', models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='', max_length=20)),
                ('duracion_dias', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeticiones', models.CharField(blank=True, default='', max_length=50)),
                ('descanso_segundos', models.IntegerField(blank=True, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_rutinas', to='gym.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workouts.rutina')),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
