# Generated by Django 6.1.1 on 2026-09-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('repeticiones', models.IntegerField()),
                ('tiempo_descanso', models.IntegerField()),
            ],
        ),
    ]
