# Generated by Django 6.1.1 on 2026-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('dificultad', models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='', max_length=20)),
                ('imagen_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
