# Generated by Django 6.1.1 on 2026-09-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_ejercicio'),
        ('workouts', '0003_rutina_rutinaejercicio_delete_workout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Set',
        ),
    ]
